version: '3.8'

services:
  web:
    build: .
    container_name: flask_dash_app
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresqlanalyzer/data
      - ./scripts/sql:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  data_collector:
    build: ./data_collector
    container_name: data_collector
    depends_on:
      - db

volumes:
  db_data:
